### ISSUE TITLE
function declaration hoisting

### ISSUE THREAD

**Issue by MollyAMcDonough** [learn-co-curriculum/phase-1-functions#5] opened 2022-01-31 22:49 UTC
### Canvas Link

https://learning.flatironschool.com/courses/4992/pages/review-functions?module_item_id=357178

### Concern

This section has the note "A function must be declared before it can be called. Calling exerciseByronThePoodle() before the function has been declared causes an error for JavaScript." right after the previous section said in a video that functions are hoisted fi declared with the function keyword. Does declaring only mean "const functionDeclare = function(){}"?

**Comment by lizbur10** [comment] 2022-02-03 17:19
Hi @MollyAMcDonough ! Thanks for bringing this to our attention, and sorry about the confusion!

The point of that paragraph was just that the function has to have been defined in order to be able to call it - in other words, the declaration has to exist in the code, but not necessarily *earlier in the code file* than the function call. The "before" here refers to time, not the order in which the function declaration and call appear.

Because different methods of declaring methods and the concept of hoisting have not yet been covered at this point in the written curriculum, it would have been adding unnecessary detail to cover that point. However, now that we know that the issue is brought up in one of the videos, we have edited that section of the lesson to try to clarify.

Note that the updates may not appear in your Canvas course, but you can see the changes here in GitHub. 

I'm going to go ahead and close this issue, but if you don't believe the edits clear up the confusion please feel free to reopen it.

Thanks for contributing to the Flatiron School curriculum 💙

**Closed** 2022-02-03 17:19 UTC
Labels: se curriculum
